    set_property PACKAGE_PIN V17 [get_ports din[0]]
    set_property IOSTANDARD LVCMOS33 [get_ports din[0]]
    set_property PACKAGE_PIN V16 [get_ports din[1]]
    set_property IOSTANDARD LVCMOS33 [get_ports din[1]]

    set_property PACKAGE_PIN W15 [get_ports en]
    set_property IOSTANDARD LVCMOS33 [get_ports en]

    set_property PACKAGE_PIN U16 [get_ports dout[0]]
    set_property IOSTANDARD LVCMOS33 [get_ports dout[0]]
    set_property PACKAGE_PIN E19 [get_ports dout[1]]
    set_property IOSTANDARD LVCMOS33 [get_ports dout[1]]
    set_property PACKAGE_PIN U19 [get_ports dout[2]]
    set_property IOSTANDARD LVCMOS33 [get_ports dout[2]]
    set_property PACKAGE_PIN V19 [get_ports dout[3]]
    set_property IOSTANDARD LVCMOS33 [get_ports dout[3]]