set_property PACKAGE_PIN W5 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]

set_property PACKAGE_PIN V17 [get_ports {a[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a[0]}]
set_property PACKAGE_PIN V16 [get_ports {a[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a[1]}]
set_property PACKAGE_PIN W16 [get_ports {a[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a[2]}]
set_property PACKAGE_PIN W17 [get_ports {a[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a[3]}]

set_property PACKAGE_PIN W15 [get_ports {b[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {b[4]}]
set_property PACKAGE_PIN V15 [get_ports {b[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {b[5]}]
set_property PACKAGE_PIN W14 [get_ports {b[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {b[6]}]
set_property PACKAGE_PIN W13 [get_ports {b[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {b[7]}]

set_property PACKAGE_PIN V2 [get_ports {sum_rest}]
set_property IOSTANDARD LVCMOS33 [get_ports {sum_rest}]

set_property PACKAGE_PIN W7 [get_ports {out[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out[0]}]
set_property PACKAGE_PIN W6 [get_ports {out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out[1]}]
set_property PACKAGE_PIN U8 [get_ports {out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out[2]}]
set_property PACKAGE_PIN V8 [get_ports {out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out[3]}]
set_property PACKAGE_PIN U5 [get_ports {out[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out[4]}]
set_property PACKAGE_PIN V5 [get_ports {out[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out[5]}]
set_property PACKAGE_PIN U7 [get_ports {out[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out[6]}]

set_property PACKAGE_PIN U2 [get_ports {transistor[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {transistor[0]}]
set_property PACKAGE_PIN U4 [get_ports {transistor[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {transistor[1]}]
set_property PACKAGE_PIN V4 [get_ports {transistor[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {transistor[2]}]
set_property PACKAGE_PIN W4 [get_ports {transistor[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {transistor[3]}]